cart/urls.py
from django.contrib import admin
from django.urls import path, include
from cart import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
         name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

# i18n_patterns: for use different urls depend on the languages /en or /es
# _(..): for convert the english urls to spanish urls when use /es
urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path(_('cart/'), include('cart.urls', namespace='cart')),  # should be upper shop app
    path(_('payment/'), include('payment.urls', namespace='payment')),  # should be upper shop app
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),  # should be upper shop app
    path('rosetta/', include('rosetta.urls')),  # should be upper shop app
    path('', include('shop.urls', namespace='shop')),
    path(_('orders/'), include('orders.urls', namespace='orders')),

)

# you can add more urls without i18n
# for confirm the static paths
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path, include
from shop import views

app_name = 'shop'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),

]

shop/models.py
from django.db import models
from autoslug import AutoSlugField
from django.urls import reverse
from parler.models import TranslatableModel, TranslatedFields


# Create your models here.


class Category(TranslatableModel):

    # make another table for these fields
    # and have multiple value for each field
    # depend on the language
    translations = TranslatedFields(
        name=models.CharField(max_length=200, db_index=True),
        slug=AutoSlugField(unique=True)
    )

    class Meta:
        # can't order translations fields
        # You can filter by translated fields in queries
        # ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(TranslatableModel):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    translations = TranslatedFields(
        name=models.CharField(max_length=200, db_index=True),
        slug=AutoSlugField(db_index=True, max_length=200),
        description=models.TextField(blank=True)
    )

    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # can't order translations fields
    # You can filter by translated fields in queries
    # also does not provide support
    # to validate index_together
    # class Meta:
    #   ordering = ('name',)
    #   index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from .recommender import Recommender


def product_list(request, category_slug=None):
    category = None
    products = Product.objects.filter(available=True)
    categories = Category.objects.all()
    if category_slug:
        # get category from the url depend on the language
        language = request.LANGUAGE_CODE
        category = get_object_or_404(Category,
                                     translations__language_code=language,
                                     translations__slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {
        'category': category,
        'categories': categories,
        'products': products,
    })


def product_detail(request, id, slug):
    # get product from the url depend on the language
    language = request.LANGUAGE_CODE
    product = get_object_or_404(Product,
                                translations__language_code=language,
                                id=id,
                                translations__slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()

    # for get the recommenders products for current product
    r = Recommender()
    recommended_products = r.suggest_products_for([product], 4)

    return render(request,
                  'shop/product/detail.html',
                  {
                      'product': product,
                      'cart_product_form': cart_product_form,
                      'recommended_products': recommended_products,
                  })

shop/templates/shop/product/base.html
{% load static %}
<!DOCTYPE html>
<html>
 <head>
 <meta charset="utf-8" />
 <title>{% block title %}My shop{% endblock %}</title>
 <link href="{% static "css/base.css" %}" rel="stylesheet">
 </head>
 <body>
 <div id="header">
 <a href="/" class="logo">My shop</a>
 </div>
 <div id="subheader">

 <div class="cart">
{% with total_items=cart|length %}
  {% if total_items > 0 %}
      Cart: <a href="{% url 'cart:cart_detail' %}">
      {{ total_items }} item{{ total_items|pluralize }}
      , ${{ cart.get_total_price }}
      </a>
    {% else %}
    Cart is empty!
    {% endif %}
 {% endwith %}

 </div>


 </div>
 <div id="content">
 {% block content %}
 {% endblock %}
 </div>
 </body>
</html>

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}<!-- always should be at the beginning -->


{% load i18n %}
{% load l10n %}


{% load static %}
{% block title %}
 {{ product.name }}
{% endblock %}
{% block content %}
 <div class="product-detail">
 <img src="
 {% if product.image %}
 {{ product.image.url }}
 {% else %}
 {% static 'img/no_image.png' %}
 {% endif %}
"/>
 <h1>{{ product.name }}</h1>
 <h2>
 <a href="{{ product.category.get_absolute_url }}">
 {{ product.category }}
 </a>
 </h2>
 <p class="price">${{ product.price }}</p>

 <p class="">Posted on:
 <!-- This for print the date in format depend on the country -->
     {% localize %}
     {{ product.created }}
     {% endlocalize %}

 <!-- Other formats you can use it for localize the variables
 {% localize on %}
 {{ product.created }}
{% endlocalize %}
{% localize off %}
 {{ product.created }}
{% endlocalize %}

{{ product.created|localize }}
{{ product.created|unlocalize }}

 -->


 </p>
 <!-- for add the product in the cart -->
 <form action="{% url 'cart:cart_add' product.id %}" method="post">
     {{ cart_product_form }}
 {% csrf_token %}
 <input type="submit" value="{% trans 'Add to cart' %}">
</form>


 {{ product.description|linebreaks }}

 <!-- Recommendations-->
 {% if recommended_products %}
 <div class="recommendations">
 <h3>{% trans "People who bought this also bought" %}</h3>
 {% for p in recommended_products %}
 <div class="item">
 <a href="{{ p.get_absolute_url }}">
 <img src="
 {% if p.image %}
 {{ p.image.url }}
 {% else %}
 {% static 'img/no_image.png' %}
  {% endif %}"
  alt="">
 </a>
 <p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
 </div>
 {% endfor %}
 </div>
{% endif %}


 </div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}{% trans "Products" %}{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar">
    <h3>{% trans "Categories" %}</h3>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url "shop:product_list" %}">{% trans "All" %}</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}{% trans "Products" %}{% endif %}</h1>
    {% for product in products %}
      <div class="item">
        <a href="{{ product.get_absolute_url }}">
          <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
        <br>
        ${{ product.price }}
      </div>
    {% endfor %}
  </div>
{% endblock %}